# Generated by Django 6.0.8 on 2026-09-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_emaildeliveryquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='delivery_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='dispatch_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
