# Generated by Django 6.0.8 on 2026-09-15 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_titles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='viewhistory',
            index=models.Index(fields=['anime', 'user', '-viewed_at'], name='catalog_view_user_idx'),
        ),
        migrations.AddIndex(
            model_name='viewhistory',
            index=models.Index(fields=['anime', 'ip_address', '-viewed_at'], name='catalog_view_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='viewhistory',
            index=models.Index(fields=['user', '-viewed_at'], name='catalog_view_history_idx'),
        ),
    ]
